name: Build and Publish Base Container Image

on:
  push:
    branches: [main]

jobs:
  build-and-push-docker-image:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Current Date
        run: echo "NOW=$(date +'%m%d%Y')" >> $GITHUB_ENV

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfiles/ubuntu2004
          platforms: linux/amd64,linux/arm64
          tags: |
            rpsene/rpsene-riscv-poc-image:latest
          push: ${{ github.event_name != 'pull_request' }}